- name: Set directories
  set_fact:
    kit_path: "/home/{{username}}/disposito_kit"

- name: Create kit directory
  file:
    path: "{{kit_path}}"
    state: directory
    mode: 0777
    owner: "{{username}}"

- name: Create temporary file
  tempfile:
    state: file
  register: resolved_executor

- name: Generating component executor
  template:
    src: "{{role_path}}/common/component-executor.yaml"
    dest: "{{resolved_executor.path}}"
    owner: "{{username}}"
    mode: 0777
  vars:
    type: "tasks_only"
    root_path: "{{role_path}}"
  delegate_to: "localhost"

- name: Run components
  include_tasks: "{{resolved_executor.path}}"





