- name: Set kit directory
  set_fact:
    kit_path: "/home/{{username}}/disposito_kit"
    executor_path: "{{role_path}}/component-executor-resolved.yaml"

- name: Set more vars
  set_fact:
    daemon_components: []

- name: Set variation directory
  set_fact:
    variation_path: "{{role_path}}/systems/{{system}}/variations/{{variation}}"
    system_path: "{{role_path}}/systems/{{system}}/variations/"
    common_path: "{{role_path}}/systems/{{system}}/variations/common/"

- name: Create kit directory
  file:
    path: "{{kit_path}}"
    state: directory
    mode: 0777
    owner: "{{username}}"

- name: Create kit subdirectories
  file:
    dest: "{{kit_path}}/{{item}}"
    state: "directory"
    mode: 0777
  with_items:
    - "daemon"
    - "helpers"

- name: Generate executor
  template:
    src: "{{role_path}}/tasks/executor.yaml"
    dest: "{{executor_path}}"
    mode: 0777
  delegate_to: "localhost"

- name: Run components
  include_tasks: "{{executor_path}}"

- name: Install daemon components
  include_tasks: "{{common_path}}/daemon/install-daemon.yaml"

- name: Delete templates
  file:
    path: "{{executor_path}}"
    state: absent



