- name: Build component path
  set_fact:
    comp_path: "{{kit_path}}/daemon/system-boot-daemon.yaml"

- name: Copy required daemon files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{ username }}"
    mode: 0777
  with_items:
    - src: "./system-boot-daemon.yaml"
      dest: "{{kit_path}}/daemon/system-boot-daemon.yaml"
    - src: "../../common/get-userid.yaml"
      dest: "{{kit_path}}/helpers/get-userid.yaml"

- name: Copy required daemon templates
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{ username }}"
    mode: 0777
  with_items:
    - src: "{{common_path}}/data/login.service"
      dest: "{{kit_path}}/login.service"

- name: Register daemon component
  set_fact:
    daemon_components: "{{daemon_components + [comp_path]}}"


