
- name: Prepare vars file from template.
  template:
    src: vars/main.j2
    dest: /tmp/vars.yaml
    lstrip_blocks: true
    trim_blocks: true

- name: Include vars
  include_vars: "/tmp/vars.yaml"

- name: Running before build hook
  include_tasks: "{{hooks['on_build']}}"
  when: operation in ['create']

- name: Build podman image
  containers.podman.podman_image:
    name: "{{image_name}}"
    path: "{{config_path}}"
    state: "{{image_state}}"
    build:
      format: docker
      cache: false
  when: operation in ['create']

- name: Manage container
  containers.podman.podman_container:
    name:  "{{container_name}}"
    image: "{{image_name}}"
    state: "{{container_state}}"
    device: "{{arguments.device}}"
    cap_add: "{{arguments.cap_add}}"
    security_opt: "{{arguments.security_opt}}"
    volume: "{{arguments.volume}}"
    cmd_args: "{{arguments.cmd_args}}"
    disable_recreate: "{{ 
        true if operation in ['start'] else false
      }}"
    interactive: true
    command: "/usr/sbin/init"
  when: operation in ['create', 'start']

- name: Adding new container to hosts
  add_host:
    name: "{{container_name}}"
    ansible_user: "root"
    ansible_become: true
    ansible_password: "root"
    ansible_become_password: "root"
    ansible_become_user: "root"
    ansible_become_flags: "-s -H"
    ansible_host: "{{container_name}}"
    ansible_connection: podman
  when: operation in ['create']

- name: Copy over host user files
  copy:
    src: "{{item}}"
    dest: "{{item}}"
    mode: '0777'
  delegate_to: "{{container_name}}"
  when: "'copy_host_user' in vars and operation in ['create']"
  with_items:
    - "/etc/group"
    - "/etc/passwd"
    - "/etc/shadow"

- name: Remove host user from host files
  lineinfile:
    path: "{{item}}"
    regexp: "^{{host_user}}.+" 
    state: absent
  delegate_to: "{{container_name}}"
  with_items:
  - "/etc/group"
  - "/etc/passwd"
  - "/etc/shadow"
  when: "'copy_host_user' in vars and operation in ['create']"

- name: Running on create hook
  include_tasks: "{{hooks['on_create']}}"
  when: operation in ['create']

- name: Running on start hook
  include_tasks: "{{hooks['on_start']}}"
  when: operation in ['start']