- name: Bootstrap container
  block:
    - name: Configure mirror list
      shell: |
        echo '[multilib]' >> /etc/pacman.conf
        echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
        rm /etc/pacman.d/mirrorlist
        touch /etc/pacman.d/mirrorlist

    - name: Copy mirror list
      copy:
        src: "../config/mirrorlist"
        dest: "/etc/pacman.d/mirrorlist"

    - name: Copy helper scripts
      copy:
        src: "../config/{{item}}"
        dest: "/"
        mode: '0777'
      with_items:
        - env-setup.sh
        - disable-logind.sh
        - attach-host-xserver.sh
        - start-xserver.sh

    - name: Setup pacman keyring
      shell: |
        pacman-key --init
        pacman-key --populate archlinux
        pacman --noconfirm -Sy archlinux-keyring && pacman --noconfirm -Su
        pacman --noconfirm -S archlinux-keyring
        pacman --noconfirm -S sudo

    - name: Relax security limits
      shell: |
        echo "$user - nice - 20" >> /etc/security/limits.conf

    - name: Setup users
      shell: |
        
        echo "root:root" | chpasswd
        echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        echo "{{container_username}} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
        sudo usermod -aG audio {{container_username}}
  
  become: yes
  become_user: "root"
  delegate_to: "{{container_name}}"

- name: Setup system as new user
  block:
    - name: Disable logind 
      shell: |
        /disable-logind.sh

    - name: Update base system
      shell: |
        sudo pacman --noconfirm -Syu
        sudo pacman --noconfirm -S base-devel git
        sudo pacman --noconfirm -Syu archlinux-keyring

    - name: Install paru
      shell: |
        git clone https://aur.archlinux.org/paru.git
        cd paru
        makepkg -sri --needed --noconfirm
      args:
          chdir: "/home/{{container_username}}"

    - name: Copy config files
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
      with_items:
        - src: "../config/xorg.conf"
          dest: "/etc/X11/xorg.conf"
        - src: "../config/Xwrapper.config"
          dest: "/etc/X11/Xwrapper.config"
        - src: "../config/config.ini"
          dest: "/etc/ly/"
        - src: "../config/xinitrc"
          dest: "/etc/X11/xinit/xinitrc"
        - src: "../config/xserverrc"
          dest: "/etc/X11/xinit/xserverrc"
    
    - name: Copy files
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
      with_items:
        - src: "../config/ly"
          dest: "/usr/bin/"

    - name: Install packages
      shell: "sudo pacman -S --noconfirm {{item}}"
      with_items:
        - xorg
        - xorg-xinit
        - xterm
        - xf86-input-evdev
        - openbox
        - xorg-fonts-misc
        - ttf-dejavu
        - nano
        - htop
        - wine-staging
        - winetricks
        - giflib
        - lib32-giflib
        - libpng
        - lib32-libpng
        - libldap
        - lib32-libldap
        - gnutls
        - lib32-gnutls
        - mpg123
        - lib32-mpg123
        - openal
        - lib32-openal
        - v4l-utils
        - lib32-v4l-utils
        - libpulse
        - lib32-libpulse
        - alsa-plugins
        - lib32-alsa-plugins
        - alsa-lib
        - lib32-alsa-lib
        - libjpeg-turbo
        - lib32-libjpeg-turbo
        - libxcomposite
        - lib32-libxcomposite
        - libxinerama
        - lib32-libxinerama
        - ncurses
        - lib32-ncurses
        - opencl-icd-loader
        - lib32-opencl-icd-loader
        - libxslt
        - lib32-libxslt
        - libva
        - lib32-libva
        - gtk3
        - lib32-gtk3
        - gst-plugins-base-libs
        - lib32-gst-plugins-base-libs
        - vulkan-icd-loader
        - lib32-vulkan-icd-loader
        - cups
        - samba
        - dosbox
        - wireplumber
        - rtkit
        - alsa
        - alsa-firmware
        - alsa-utils
        - pipewire-alsa

    - name: Install paru packages
      shell: "paru -S --noconfirm {{item}}"
      with_items:
        - nano
        - steam
        - wget
        - ly
        - xf86-input-evdev
        - openbox

    - name: Enable ly
      shell: sudo systemctl enable ly

  become: yes
  become_user: "{{container_username}}"
