- name: Get user id 
  include_tasks: "{{kit_path}}/get-userid.yaml"

- name: Generate login service
  template:
    src: "{{kit_path}}/login.service"
    dest: "/etc/systemd/system/login.service"
    mode: 0777

- name: start login service
  systemd:
    enabled: true
    name: login
    state: started

- name: Create bash login if it does not exist
  command: "touch /home/{{username}}/.bash_login"
  args:
    creates: /home/{{username}}/.bash_login

- name: Set DBUS path
  lineinfile:
    path: /etc/environment
    line: "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/{{user_id}}/bus"
    state: present

- name: Set display variable
  lineinfile:
    path: /etc/environment
    line: "DISPLAY=:0"
    state: present
    
- name: Disable getty
  systemd:
    name: getty@{{item}}.service
    state: stopped
    masked: true
  ignore_errors: true
  with_items:
    - 1
    - 2
    - 3
    - 4

- name: Disable logind
  systemd:
    name: systemd-logind.service 
    state: stopped
    masked: true

- name: Start user service
  systemd:
    name: "user@{{ user_id }}"
    state: started

