- hosts: localhost
  become: yes
  become_user: root
  tasks:

    - import_role:
        name: container
      vars:
        container_name: "{{container_name}}"
        container_config: "../container_configs/archlinux_with_xserver"
        image_name: archlinux_with_xserver
        graphics: x-server
        sound: pipewire
        nested_containers: false
        gpu: nvidia
        copy_host_user: true
        tty: 2
        operation: "{{desired_operation}}"
        container_username: "linuxdev"
        container_password: "root"
        host_username: "linuxdev"
        additional_volumes:
          - src: "/home/linuxdev/container_drive/"
            dest: "/container_drive/"


- hosts: "{{container_name}}"
  connection: podman
  become: yes
  become_user: root
  tasks:

    - import_role:
        name: environment
      vars:
        system: linux
        variation: arch-full-install
        username: linuxdev
        password: root
        components:
          - name: system-boot
          - name: system-setup
            params:
              gpu_driver: nvidia
              login_tty: 2
      when: desired_operation not in ['start', 'destroy']


- hosts: "{{container_name}}"
  connection: podman
  become: yes
  become_user: root
  tasks:

    - import_role:
        name: container
      vars:
        container_name: "{{container_name}}"
        operation: "restart"
      when: desired_operation not in ['destroy']

