- hosts: localhost
  become: yes
  become_user: root
  tasks:

    - import_role:
        name: container
      vars:
        container_name: "{{container_name}}"
        build_tasks: "../containers/archlinux_with_xserver/build.yaml"
        create_tasks: "../containers/archlinux_with_xserver/create.yaml"
        start_tasks: "../containers/archlinux_with_xserver/start.yaml"
        image_name: archlinux_with_xserver
        graphics: x-server
        sound: pipewire
        nested_containers: true
        gpu: nvidia
        copy_host_user: true
        tty: 2
        operation: "{{desired_operation}}"
        container_username: "linuxdev"
        container_password: "root"
        host_username: "linuxdev"
        additional_volumes:
          - src: "/home/linuxdev/host_drive/"
            dest: "/host_drive/"


- hosts: "{{container_name}}"
  connection: podman
  become: yes
  become_user: root
  tasks:
    - import_role:
        name: environment
      vars:
        username: linuxdev
        password: root
        components:
          - name: linux-arch/system-boot
          - name: linux-arch/system-setup
            params:
              gpu_driver: nvidia
              login_tty: 2
              additional_packages:
                - steam
                - openbox
                - chromium

      when: desired_operation not in ['start', 'destroy']


- hosts: "localhost"
  connection: local
  become: yes
  become_user: root
  tasks:
    - import_role:
        name: container
      vars:
        container_name: "{{container_name}}"
        operation: "restart"
      when: desired_operation not in ['destroy']

