- hosts: "localhost"
  connection: local
  become: yes
  become_user: {{username}}
  tasks:

    - import_role:
        name: wine
      vars:

        components_dir: "/home/wine_components/"
        prefixes_dir:   "/home/wine_prefixes/"

        runtime:
          library_32bit_path: "/lib/"
          library_64bit_path: "/lib64"
          
        component_variants:
          dxvk:
            debug_build:
              breadcrumbs: true
            perf_build:
              breadcrumbs: false
              logging: disabled

        prefix_types:

          misc_gaming:
            execs:
              steam:
                exe_path: "c:\Program Files (x86)\Steam\steam.exe"

            components:
              - build: latest_wine_tkg_build
                params:
                  disable_audio: true
              - build: latest_vkd3d_proton
                params:
                  spoof_amd_gpu: true

            tools:
              winetricks:
                install:
                  - dotnet48
                remove:
                  - mono

            env_var_sets:
              - nvidia
            env_vars:
              - name: "WINE_ADDRESS_AWARE"
                val: 1

            dll_override_sets:
            dll_overrides:
              - name: mshtml
                val: "d"
              - name: winemenubuilder
                val: ""
              - name: test
                val: "b,n"
                app: "abc123"
            
            reg_key_sets:
              - visual_studio
            reg_keys:
              - key: "abc123"
                type: "string"
                val: "aaa"


