- name: Set some vars
  set_fact:
    kit_path: "/home/{{ansible_user}}/disposito_kit"

- name: Creates kit directories
  file:
    path: "{{item}}"
    state: directory
  args:
    creates: "{{item}}"
  with_items:
    - "{{kit_path}}"
    - "{{kit_path}}/playbooks"
    - "{{kit_path}}/files"
    
- name: Build templates
  template:
    src: "{{ item }}"
    dest: "{{kit_path}}/files/"
    owner: "{{ ansible_user }}"
    mode: 0777
  with_fileglob:
    - "{{role_path}}/templates/*"
    
- name: Copy playbooks
  template:
    src: "{{ item }}"
    dest: "{{kit_path}}/playbooks/"
    owner: "{{ ansible_user }}"
    mode: 0777
  with_fileglob:
    - "{{role_path}}/playbooks/*"

- name: Generate run playbook
  template:
    src: "{{role_path}}/templates/run-disposito.yaml.jinja"
    dest: "{{kit_path}}/run-disposito.yaml"
    owner: "{{ ansible_user }}"
    mode: 0777

- name: Setup services
  block:

    - name: Copy over disposito service
      template:
        src: "{{kit_path}}/files/disposito.service"
        dest: "/etc/systemd/system/disposito.service"
        mode: 0777
      args:
        creates: "/etc/systemd/system/disposito.service"

    - name: Get user id (raw)
      shell: id -u {{ ansible_user }}
      register: raw_user_id

    - name: Get user id
      set_fact: 
        user_id: "{{raw_user_id.stdout_lines[0]}}"

  become: true
  become_user: root
  become_method: sudo